title: WORKFLOW.CH Status
buildFuture: true
defaultContentLanguage: de
languageCode: de
baseURL: https://status.workflow.ch
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: Jan 2 — 15:04 UTC
  down: "#e60000"
  systems:
    - name: Webseite
      category: Plattform
      description: Allgemeine Erreichbarkeit der Webanwendung
    - name: E-Mailversand
      category: Plattform
      description: Versand von E-Mails über die Webanwendung
    - name: Live-Benachrichtigungen
      category: Plattform
      description: Live-Benachrichtigungen in der Webanwendung
    - name: Dateiverwaltung
      category: Plattform
      description: Dateiverwaltung (Erreichbarkeit sowie Upload und Generierung von
        neuen Dateien über die Webanwendung)
  dateFormat: Mon, 02 Jan 2006 15:04:05 MST
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/logo_inverted_inklschriftzug.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Plattform
      description: ""
  description: Wir überwachen ständig den Status unserer Dienste. Falls es zu
    Unterbrechungen kommt, werden wir über diese Seite darüber informieren.
  enableCustomHTML: true
  useLargeHeaderDesign: false
